### ISSUE TITLE
any data and code for this amazing analysis?

### ISSUE THREAD

**Issue by liamxg** [MurrellGroup/lineages#1]
@murrellb

**Comment by murrellb** [comment]
We've been meaning to clean the Julia code up to share it, but haven't quite got there yet, so currently this is just the outputs for now. The methods are explained, a little, at the bottom of the readme though. The data are from GISAID.

There is some code up for a related (but simpler) analysis here: https://github.com/MurrellGroup/MultinomialLogisticGrowth

**Comment by murrellb** [comment]
We only use Julia.

For similar analyses in R, this is one repository I'm aware of: https://github.com/tomwenseleers/LineageExplorer
